name: CI with Manual Approval

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Running build..."

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: lokeshlish  # replace with your GitHub username(s)
          minimum-approvals: 1
          issue-title: "Manual approval needed for deploy"
          issue-body: "Please approve or deny this workflow run."

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy step
        run: echo "Deploying after approval..."
