name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building app..."

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging..."

  approval:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval before deploy
        uses: trstringer/manual-approval@v1
        with:
          approvers: lokeshlish      # GitHub usernames
          minimum-approvals: 1
          issue-title: "Deploy approval required"
          issue-body: "Approve this to deploy the latest image to production."

  deploy-production:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production..."
