name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building app..."

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging..."

  approval:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval before deploy
        uses: codex-/await-approval-action@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          approvers: lokeshlish           # GitHub username(s) allowed to approve
          instructions: "Please approve to continue deploying to production."

  deploy-production:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production..."
